// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_access.proto

package com.cit.data.grcp;

public final class DataAccess {
  private DataAccess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cit_data_grcp_TweetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cit_data_grcp_TweetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cit_data_grcp_TweetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cit_data_grcp_TweetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021data_access.proto\022\021com.cit.data.grcp\"\034" +
      "\n\014TweetRequest\022\014\n\004flag\030\001 \001(\010\"F\n\rTweetRes" +
      "ponse\022\n\n\002id\030\001 \001(\003\022\014\n\004data\030\002 \001(\t\022\014\n\004user\030" +
      "\003 \001(\t\022\r\n\005tweet\030\004 \001(\t2^\n\014TweetService\022N\n\007" +
      "request\022\037.com.cit.data.grcp.TweetRequest" +
      "\032 .com.cit.data.grcp.TweetResponse0\001B\002P\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cit_data_grcp_TweetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cit_data_grcp_TweetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cit_data_grcp_TweetRequest_descriptor,
        new String[] { "Flag", });
    internal_static_com_cit_data_grcp_TweetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cit_data_grcp_TweetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cit_data_grcp_TweetResponse_descriptor,
        new String[] { "Id", "Data", "User", "Tweet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
