// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_access.proto

package com.cit.data.grcp;

public interface TweetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cit.data.grcp.TweetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool flag = 1;</code>
   */
  boolean getFlag();
}
