// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_access.proto

package com.cit.data.grcp;

public interface TweetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cit.data.grcp.TweetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string data = 2;</code>
   */
  String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>string user = 3;</code>
   */
  String getUser();
  /**
   * <code>string user = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string tweet = 4;</code>
   */
  String getTweet();
  /**
   * <code>string tweet = 4;</code>
   */
  com.google.protobuf.ByteString
      getTweetBytes();
}
